services:
  timeship:
    container_name: timeship
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./:/mnt/:ro,z
    restart: unless-stopped

  # Local Docker registry for "task docker:multiarch:push:local"
  registry:
    image: registry:2
    ports:
      - 5000:5000
    volumes:
      - ./dist/registry:/var/lib/registry
